// Do not edit this file; automatically generated by gulp.
'use strict';


Blockly.Ks = new Blockly.Generator("Ks");
Blockly.Ks.addReservedWords("break,case,catch,class,const,continue,debugger,default,delete,do,else,export,extends,finally,for,function,if,import,in,instanceof,new,return,super,switch,this,throw,try,typeof,var,void,while,with,yield,enum,implements,interface,let,package,private,protected,public,static,await,null,true,false,arguments," 
	+ Object.getOwnPropertyNames(Blockly.utils.global).join(","));
Blockly.Ks.ORDER_ATOMIC = 0;
Blockly.Ks.ORDER_NEW = 1.1;
Blockly.Ks.ORDER_MEMBER = 1.2;
Blockly.Ks.ORDER_FUNCTION_CALL = 2;
Blockly.Ks.ORDER_INCREMENT = 3;
Blockly.Ks.ORDER_DECREMENT = 3;
Blockly.Ks.ORDER_BITWISE_NOT = 4.1;
Blockly.Ks.ORDER_UNARY_PLUS = 4.2;
Blockly.Ks.ORDER_UNARY_NEGATION = 4.3;
Blockly.Ks.ORDER_LOGICAL_NOT = 4.4;
Blockly.Ks.ORDER_TYPEOF = 4.5;
Blockly.Ks.ORDER_VOID = 4.6;
Blockly.Ks.ORDER_DELETE = 4.7;
Blockly.Ks.ORDER_AWAIT = 4.8;
Blockly.Ks.ORDER_EXPONENTIATION = 5;
Blockly.Ks.ORDER_MULTIPLICATION = 5.1;
Blockly.Ks.ORDER_DIVISION = 5.2;
Blockly.Ks.ORDER_MODULUS = 5.3;
Blockly.Ks.ORDER_SUBTRACTION = 6.1;
Blockly.Ks.ORDER_ADDITION = 6.2;
Blockly.Ks.ORDER_BITWISE_SHIFT = 7;
Blockly.Ks.ORDER_RELATIONAL = 8;
Blockly.Ks.ORDER_IN = 8;
Blockly.Ks.ORDER_INSTANCEOF = 8;
Blockly.Ks.ORDER_EQUALITY = 9;
Blockly.Ks.ORDER_BITWISE_AND = 10;
Blockly.Ks.ORDER_BITWISE_XOR = 11;
Blockly.Ks.ORDER_BITWISE_OR = 12;
Blockly.Ks.ORDER_LOGICAL_AND = 13;
Blockly.Ks.ORDER_LOGICAL_OR = 14;
Blockly.Ks.ORDER_CONDITIONAL = 15;
Blockly.Ks.ORDER_ASSIGNMENT = 16;
Blockly.Ks.ORDER_YIELD = 17;
Blockly.Ks.ORDER_COMMA = 18;
Blockly.Ks.ORDER_NONE = 99;
Blockly.Ks.ORDER_OVERRIDES = [
    [Blockly.Ks.ORDER_FUNCTION_CALL, Blockly.Ks.ORDER_MEMBER],
    [Blockly.Ks.ORDER_FUNCTION_CALL, Blockly.Ks.ORDER_FUNCTION_CALL],
    [Blockly.Ks.ORDER_MEMBER, Blockly.Ks.ORDER_MEMBER],
    [Blockly.Ks.ORDER_MEMBER, Blockly.Ks.ORDER_FUNCTION_CALL],
    [Blockly.Ks.ORDER_LOGICAL_NOT, Blockly.Ks.ORDER_LOGICAL_NOT],
    [Blockly.Ks.ORDER_MULTIPLICATION, Blockly.Ks.ORDER_MULTIPLICATION],
    [Blockly.Ks.ORDER_ADDITION,
        Blockly.Ks.ORDER_ADDITION
    ],
    [Blockly.Ks.ORDER_LOGICAL_AND, Blockly.Ks.ORDER_LOGICAL_AND],
    [Blockly.Ks.ORDER_LOGICAL_OR, Blockly.Ks.ORDER_LOGICAL_OR]
];
Blockly.Ks.init = function(a) {
    Blockly.Ks.definitions_ = Object.create(null);
    Blockly.Ks.functionNames_ = Object.create(null);
    Blockly.Ks.variableDB_ ? Blockly.Ks.variableDB_.reset() : Blockly.Ks.variableDB_ = new Blockly.Names(Blockly.Ks.RESERVED_WORDS_);
    Blockly.Ks.variableDB_.setVariableMap(a.getVariableMap());
    for (var b = [], c = Blockly.Variables.allDeveloperVariables(a), d = 0; d < c.length; d++) b.push(Blockly.Ks.variableDB_.getName(c[d], Blockly.Names.DEVELOPER_VARIABLE_TYPE));
    a = Blockly.Variables.allUsedVarModels(a);
    for (d = 0; d < a.length; d++) b.push(Blockly.Ks.variableDB_.getName(a[d].getId(), Blockly.VARIABLE_CATEGORY_NAME));
    // console.log(b);
    if(b.length > 1) {
    	var varStr = "";
    	for (var i = 0; i < b.length; i++) {
    		varStr += "变量 " + b[i] + " = \"\";\n"
    	}
    	b.length && (Blockly.Ks.definitions_.variables = varStr);
    } else {
    	b.length && (Blockly.Ks.definitions_.variables = "变量 " + b.join(", ") + " = \"\";");
    }
};
Blockly.Ks.finish = function(a) {
    var b = [],
        c;
    for (c in Blockly.Ks.definitions_) b.push(Blockly.Ks.definitions_[c]);
    delete Blockly.Ks.definitions_;
    delete Blockly.Ks.functionNames_;
    Blockly.Ks.variableDB_.reset();
    return b.join("\n\n") + "\n\n\n" + a
};
Blockly.Ks.scrubNakedValue = function(a) {
    return a + ";\n"
};
Blockly.Ks.quote_ = function(a) {
    a = a.replace(/\\/g, "\\\\").replace(/\n/g, "\\\n").replace(/'/g, "\\'");
    return "'" + a + "'"
};
Blockly.Ks.multiline_quote_ = function(a) {
    return a.split(/\n/g).map(Blockly.Ks.quote_).join(" + '\\n' +\n")
};
Blockly.Ks.scrub_ = function(a, b, c) {
    var d = "";
    if (!a.outputConnection || !a.outputConnection.targetConnection) {
        var e = a.getCommentText();
        e && (e = Blockly.utils.string.wrap(e, Blockly.Ks.COMMENT_WRAP - 3), d += Blockly.Ks.prefixLines(e + "\n", "// "));
        for (var f = 0; f < a.inputList.length; f++) a.inputList[f].type == Blockly.INPUT_VALUE && (e = a.inputList[f].connection.targetBlock()) && (e = Blockly.Ks.allNestedComments(e)) && (d += Blockly.Ks.prefixLines(e, "// "))
    }
    a = a.nextConnection && a.nextConnection.targetBlock();
    c = c ? "" : Blockly.Ks.blockToCode(a);
    return d + b + c
};
Blockly.Ks.getAdjusted = function(a, b, c, d, e) {
    c = c || 0;
    e = e || Blockly.Ks.ORDER_NONE;
    a.workspace.options.oneBasedIndex && c--;
    var f = a.workspace.options.oneBasedIndex ? "1" : "0";
    a = 0 < c ? Blockly.Ks.valueToCode(a, b, Blockly.Ks.ORDER_ADDITION) || f : 0 > c ? Blockly.Ks.valueToCode(a, b, Blockly.Ks.ORDER_SUBTRACTION) || f : d ? Blockly.Ks.valueToCode(a, b, Blockly.Ks.ORDER_UNARY_NEGATION) || f : Blockly.Ks.valueToCode(a, b, e) || f;
    if (Blockly.isNumber(a)) a = Number(a) + c, d &&
        (a = -a);
    else {
        if (0 < c) {
            a = a + " + " + c;
            var g = Blockly.Ks.ORDER_ADDITION
        } else 0 > c && (a = a + " - " + -c, g = Blockly.Ks.ORDER_SUBTRACTION);
        d && (a = c ? "-(" + a + ")" : "-" + a, g = Blockly.Ks.ORDER_UNARY_NEGATION);
        g = Math.floor(g);
        e = Math.floor(e);
        g && e >= g && (a = "(" + a + ")")
    }
    return a
};
Blockly.Ks.colour = {};
Blockly.Ks.colour_picker = function(a) {
    return [Blockly.Ks.quote_(a.getFieldValue("COLOUR").replace("#","")), Blockly.Ks.ORDER_ATOMIC]
};
Blockly.Ks.colour_random = function(a) {
    return [Blockly.Ks.provideFunction_("colourRandom", ["function " + Blockly.Ks.FUNCTION_NAME_PLACEHOLDER_ + "() {", "  var num = Math.floor(Math.random() * Math.pow(2, 24));", "  return '#' + ('00000' + num.toString(16)).substr(-6);", "}"]) + "()", Blockly.Ks.ORDER_FUNCTION_CALL]
};
Blockly.Ks.colour_rgb = function(a) {
    var b = Blockly.Ks.valueToCode(a, "RED", Blockly.Ks.ORDER_COMMA) || 0,
        c = Blockly.Ks.valueToCode(a, "GREEN", Blockly.Ks.ORDER_COMMA) || 0;
    a = Blockly.Ks.valueToCode(a, "BLUE", Blockly.Ks.ORDER_COMMA) || 0;
    return [Blockly.Ks.provideFunction_("colourRgb", ["function " + Blockly.Ks.FUNCTION_NAME_PLACEHOLDER_ + "(r, g, b) {", "  r = Math.max(Math.min(Number(r), 100), 0) * 2.55;", "  g = Math.max(Math.min(Number(g), 100), 0) * 2.55;",
        "  b = Math.max(Math.min(Number(b), 100), 0) * 2.55;", "  r = ('0' + (Math.round(r) || 0).toString(16)).slice(-2);", "  g = ('0' + (Math.round(g) || 0).toString(16)).slice(-2);", "  b = ('0' + (Math.round(b) || 0).toString(16)).slice(-2);", "  return '#' + r + g + b;", "}"
    ]) + "(" + b + ", " + c + ", " + a + ")", Blockly.Ks.ORDER_FUNCTION_CALL]
};
Blockly.Ks.colour_blend = function(a) {
    var b = Blockly.Ks.valueToCode(a, "COLOUR1", Blockly.Ks.ORDER_COMMA) || "'#000000'",
        c = Blockly.Ks.valueToCode(a, "COLOUR2", Blockly.Ks.ORDER_COMMA) || "'#000000'";
    a = Blockly.Ks.valueToCode(a, "RATIO", Blockly.Ks.ORDER_COMMA) || .5;
    return [Blockly.Ks.provideFunction_("colourBlend", ["function " + Blockly.Ks.FUNCTION_NAME_PLACEHOLDER_ + "(c1, c2, ratio) {", "  ratio = Math.max(Math.min(Number(ratio), 1), 0);", "  var r1 = parseInt(c1.substring(1, 3), 16);",
        "  var g1 = parseInt(c1.substring(3, 5), 16);", "  var b1 = parseInt(c1.substring(5, 7), 16);", "  var r2 = parseInt(c2.substring(1, 3), 16);", "  var g2 = parseInt(c2.substring(3, 5), 16);", "  var b2 = parseInt(c2.substring(5, 7), 16);", "  var r = Math.round(r1 * (1 - ratio) + r2 * ratio);", "  var g = Math.round(g1 * (1 - ratio) + g2 * ratio);", "  var b = Math.round(b1 * (1 - ratio) + b2 * ratio);", "  r = ('0' + (r || 0).toString(16)).slice(-2);", "  g = ('0' + (g || 0).toString(16)).slice(-2);", "  b = ('0' + (b || 0).toString(16)).slice(-2);",
        "  return '#' + r + g + b;", "}"
    ]) + "(" + b + ", " + c + ", " + a + ")", Blockly.Ks.ORDER_FUNCTION_CALL]
};
Blockly.Ks.lists = {};
Blockly.Ks.lists_create_empty = function(a) {
    return ["[]", Blockly.Ks.ORDER_ATOMIC]
};
Blockly.Ks.lists_create_with = function(a) {
    for (var b = Array(a.itemCount_), c = 0; c < a.itemCount_; c++) b[c] = Blockly.Ks.valueToCode(a, "ADD" + c, Blockly.Ks.ORDER_COMMA) || "null";
    return ["[" + b.join(", ") + "]", Blockly.Ks.ORDER_ATOMIC]
};
Blockly.Ks.lists_repeat = function(a) {
    var b = Blockly.Ks.provideFunction_("listsRepeat", ["function " + Blockly.Ks.FUNCTION_NAME_PLACEHOLDER_ + "(value, n) {", "  var array = [];", "  for (var i = 0; i < n; i++) {", "    array[i] = value;", "  }", "  return array;", "}"]),
        c = Blockly.Ks.valueToCode(a, "ITEM", Blockly.Ks.ORDER_COMMA) || "null";
    a = Blockly.Ks.valueToCode(a, "NUM", Blockly.Ks.ORDER_COMMA) || "0";
    return [b + "(" + c + ", " + a + ")", Blockly.Ks.ORDER_FUNCTION_CALL]
};
Blockly.Ks.lists_length = function(a) {
    return [(Blockly.Ks.valueToCode(a, "VALUE", Blockly.Ks.ORDER_MEMBER) || "[]") + ".length", Blockly.Ks.ORDER_MEMBER]
};
Blockly.Ks.lists_isEmpty = function(a) {
    return ["!" + (Blockly.Ks.valueToCode(a, "VALUE", Blockly.Ks.ORDER_MEMBER) || "[]") + ".length", Blockly.Ks.ORDER_LOGICAL_NOT]
};
Blockly.Ks.lists_indexOf = function(a) {
    var b = "FIRST" == a.getFieldValue("END") ? "indexOf" : "lastIndexOf",
        c = Blockly.Ks.valueToCode(a, "FIND", Blockly.Ks.ORDER_NONE) || "''";
    b = (Blockly.Ks.valueToCode(a, "VALUE", Blockly.Ks.ORDER_MEMBER) || "[]") + "." + b + "(" + c + ")";
    return a.workspace.options.oneBasedIndex ? [b + " + 1", Blockly.Ks.ORDER_ADDITION] : [b, Blockly.Ks.ORDER_FUNCTION_CALL]
};
Blockly.Ks.lists_getIndex = function(a) {
    var b = a.getFieldValue("MODE") || "GET",
        c = a.getFieldValue("WHERE") || "FROM_START",
        d = Blockly.Ks.valueToCode(a, "VALUE", "RANDOM" == c ? Blockly.Ks.ORDER_COMMA : Blockly.Ks.ORDER_MEMBER) || "[]";
    switch (c) {
        case "FIRST":
            if ("GET" == b) return [d + "[0]", Blockly.Ks.ORDER_MEMBER];
            if ("GET_REMOVE" == b) return [d + ".shift()", Blockly.Ks.ORDER_MEMBER];
            if ("REMOVE" == b) return d + ".shift();\n";
            break;
        case "LAST":
            if ("GET" == b) return [d + ".slice(-1)[0]", Blockly.Ks.ORDER_MEMBER];
            if ("GET_REMOVE" == b) return [d + ".pop()", Blockly.Ks.ORDER_MEMBER];
            if ("REMOVE" == b) return d + ".pop();\n";
            break;
        case "FROM_START":
            a = Blockly.Ks.getAdjusted(a, "AT");
            if ("GET" == b) return [d + "[" + a + "]", Blockly.Ks.ORDER_MEMBER];
            if ("GET_REMOVE" == b) return [d + ".splice(" + a + ", 1)[0]", Blockly.Ks.ORDER_FUNCTION_CALL];
            if ("REMOVE" == b) return d + ".splice(" + a + ", 1);\n";
            break;
        case "FROM_END":
            a = Blockly.Ks.getAdjusted(a, "AT", 1, !0);
            if ("GET" == b) return [d + ".slice(" + a + ")[0]", Blockly.Ks.ORDER_FUNCTION_CALL];
            if ("GET_REMOVE" == b) return [d + ".splice(" + a + ", 1)[0]", Blockly.Ks.ORDER_FUNCTION_CALL];
            if ("REMOVE" == b) return d + ".splice(" + a + ", 1);";
            break;
        case "RANDOM":
            d = Blockly.Ks.provideFunction_("listsGetRandomItem", ["function " + Blockly.Ks.FUNCTION_NAME_PLACEHOLDER_ + "(list, remove) {", "  var x = Math.floor(Math.random() * list.length);", "  if (remove) {", "    return list.splice(x, 1)[0];", "  } else {", "    return list[x];", "  }", "}"]) + "(" + d + ", " + ("GET" != b) + ")";
            if ("GET" == b || "GET_REMOVE" == b) return [d,
                Blockly.Ks.ORDER_FUNCTION_CALL
            ];
            if ("REMOVE" == b) return d + ";\n"
    }
    throw Error("Unhandled combination (lists_getIndex).");
};
Blockly.Ks.lists_setIndex = function(a) {
    function b() {
        if (c.match(/^\w+$/)) return "";
        var a = Blockly.Ks.variableDB_.getDistinctName("tmpList", Blockly.VARIABLE_CATEGORY_NAME),
            b = "var " + a + " = " + c + ";\n";
        c = a;
        return b
    }
    var c = Blockly.Ks.valueToCode(a, "LIST", Blockly.Ks.ORDER_MEMBER) || "[]",
        d = a.getFieldValue("MODE") || "GET",
        e = a.getFieldValue("WHERE") || "FROM_START",
        f = Blockly.Ks.valueToCode(a, "TO", Blockly.Ks.ORDER_ASSIGNMENT) || "null";
    switch (e) {
        case "FIRST":
            if ("SET" == d) return c +
                "[0] = " + f + ";\n";
            if ("INSERT" == d) return c + ".unshift(" + f + ");\n";
            break;
        case "LAST":
            if ("SET" == d) return a = b(), a + (c + "[" + c + ".length - 1] = " + f + ";\n");
            if ("INSERT" == d) return c + ".push(" + f + ");\n";
            break;
        case "FROM_START":
            e = Blockly.Ks.getAdjusted(a, "AT");
            if ("SET" == d) return c + "[" + e + "] = " + f + ";\n";
            if ("INSERT" == d) return c + ".splice(" + e + ", 0, " + f + ");\n";
            break;
        case "FROM_END":
            e = Blockly.Ks.getAdjusted(a, "AT", 1, !1, Blockly.Ks.ORDER_SUBTRACTION);
            a = b();
            if ("SET" == d) return a + (c + "[" + c + ".length - " + e +
                "] = " + f + ";\n");
            if ("INSERT" == d) return a + (c + ".splice(" + c + ".length - " + e + ", 0, " + f + ");\n");
            break;
        case "RANDOM":
            a = b();
            e = Blockly.Ks.variableDB_.getDistinctName("tmpX", Blockly.VARIABLE_CATEGORY_NAME);
            a += "var " + e + " = Math.floor(Math.random() * " + c + ".length);\n";
            if ("SET" == d) return a + (c + "[" + e + "] = " + f + ";\n");
            if ("INSERT" == d) return a + (c + ".splice(" + e + ", 0, " + f + ");\n")
    }
    throw Error("Unhandled combination (lists_setIndex).");
};
Blockly.Ks.lists.getIndex_ = function(a, b, c) {
    return "FIRST" == b ? "0" : "FROM_END" == b ? a + ".length - 1 - " + c : "LAST" == b ? a + ".length - 1" : c
};
Blockly.Ks.lists_getSublist = function(a) {
    var b = Blockly.Ks.valueToCode(a, "LIST", Blockly.Ks.ORDER_MEMBER) || "[]",
        c = a.getFieldValue("WHERE1"),
        d = a.getFieldValue("WHERE2");
    if ("FIRST" == c && "LAST" == d) b += ".slice(0)";
    else if (b.match(/^\w+$/) || "FROM_END" != c && "FROM_START" == d) {
        switch (c) {
            case "FROM_START":
                var e = Blockly.Ks.getAdjusted(a, "AT1");
                break;
            case "FROM_END":
                e = Blockly.Ks.getAdjusted(a, "AT1", 1, !1, Blockly.Ks.ORDER_SUBTRACTION);
                e = b + ".length - " + e;
                break;
            case "FIRST":
                e =
                    "0";
                break;
            default:
                throw Error("Unhandled option (lists_getSublist).");
        }
        switch (d) {
            case "FROM_START":
                a = Blockly.Ks.getAdjusted(a, "AT2", 1);
                break;
            case "FROM_END":
                a = Blockly.Ks.getAdjusted(a, "AT2", 0, !1, Blockly.Ks.ORDER_SUBTRACTION);
                a = b + ".length - " + a;
                break;
            case "LAST":
                a = b + ".length";
                break;
            default:
                throw Error("Unhandled option (lists_getSublist).");
        }
        b = b + ".slice(" + e + ", " + a + ")"
    } else {
        e = Blockly.Ks.getAdjusted(a, "AT1");
        a = Blockly.Ks.getAdjusted(a, "AT2");
        var f = Blockly.Ks.lists.getIndex_,
            g = {
                FIRST: "First",
                LAST: "Last",
                FROM_START: "FromStart",
                FROM_END: "FromEnd"
            };
        b = Blockly.Ks.provideFunction_("subsequence" + g[c] + g[d], ["function " + Blockly.Ks.FUNCTION_NAME_PLACEHOLDER_ + "(sequence" + ("FROM_END" == c || "FROM_START" == c ? ", at1" : "") + ("FROM_END" == d || "FROM_START" == d ? ", at2" : "") + ") {", "  var start = " + f("sequence", c, "at1") + ";", "  var end = " + f("sequence", d, "at2") + " + 1;", "  return sequence.slice(start, end);", "}"]) + "(" + b + ("FROM_END" == c || "FROM_START" == c ? ", " + e : "") + ("FROM_END" == d || "FROM_START" ==
            d ? ", " + a : "") + ")"
    }
    return [b, Blockly.Ks.ORDER_FUNCTION_CALL]
};
Blockly.Ks.lists_sort = function(a) {
    var b = Blockly.Ks.valueToCode(a, "LIST", Blockly.Ks.ORDER_FUNCTION_CALL) || "[]",
        c = "1" === a.getFieldValue("DIRECTION") ? 1 : -1;
    a = a.getFieldValue("TYPE");
    var d = Blockly.Ks.provideFunction_("listsGetSortCompare", ["function " + Blockly.Ks.FUNCTION_NAME_PLACEHOLDER_ + "(type, direction) {", "  var compareFuncs = {", '    "NUMERIC": function(a, b) {', "        return Number(a) - Number(b); },", '    "TEXT": function(a, b) {', "        return a.toString() > b.toString() ? 1 : -1; },",
        '    "IGNORE_CASE": function(a, b) {', "        return a.toString().toLowerCase() > b.toString().toLowerCase() ? 1 : -1; },", "  };", "  var compare = compareFuncs[type];", "  return function(a, b) { return compare(a, b) * direction; }", "}"
    ]);
    return [b + ".slice().sort(" + d + '("' + a + '", ' + c + "))", Blockly.Ks.ORDER_FUNCTION_CALL]
};
Blockly.Ks.lists_split = function(a) {
    var b = Blockly.Ks.valueToCode(a, "INPUT", Blockly.Ks.ORDER_MEMBER),
        c = Blockly.Ks.valueToCode(a, "DELIM", Blockly.Ks.ORDER_NONE) || "''";
    a = a.getFieldValue("MODE");
    if ("SPLIT" == a) b || (b = "''"), a = "split";
    else if ("JOIN" == a) b || (b = "[]"), a = "join";
    else throw Error("Unknown mode: " + a);
    return [b + "." + a + "(" + c + ")", Blockly.Ks.ORDER_FUNCTION_CALL]
};
Blockly.Ks.lists_reverse = function(a) {
    return [(Blockly.Ks.valueToCode(a, "LIST", Blockly.Ks.ORDER_FUNCTION_CALL) || "[]") + ".slice().reverse()", Blockly.Ks.ORDER_FUNCTION_CALL]
};
Blockly.Ks.logic = {};
Blockly.Ks.controls_if = function(a) {
    var b = 0,
        c = "";
    Blockly.Ks.STATEMENT_PREFIX && (c += Blockly.Ks.injectId(Blockly.Ks.STATEMENT_PREFIX, a));
    do {
        var d = Blockly.Ks.valueToCode(a, "IF" + b, Blockly.Ks.ORDER_NONE) || "false";
        var e = Blockly.Ks.statementToCode(a, "DO" + b);
        Blockly.Ks.STATEMENT_SUFFIX && (e = Blockly.Ks.prefixLines(Blockly.Ks.injectId(Blockly.Ks.STATEMENT_SUFFIX, a), Blockly.Ks.INDENT) + e);
        c += (0 < b ? " else " : "") + "如果 (" +
            d + ") {\n" + e + "}";
        ++b
    } while (a.getInput("IF" + b));
    if (a.getInput("ELSE") || Blockly.Ks.STATEMENT_SUFFIX) e = Blockly.Ks.statementToCode(a, "ELSE"), Blockly.Ks.STATEMENT_SUFFIX && (e = Blockly.Ks.prefixLines(Blockly.Ks.injectId(Blockly.Ks.STATEMENT_SUFFIX, a), Blockly.Ks.INDENT) + e), c += " else {\n" + e + "}";
    return c + "\n"
};
Blockly.Ks.controls_ifelse = Blockly.Ks.controls_if;
Blockly.Ks.logic_compare = function(a) {
    var b = {
            EQ: "==",
            NEQ: "!=",
            LT: "<",
            LTE: "<=",
            GT: ">",
            GTE: ">="
        }[a.getFieldValue("OP")],
        c = "==" == b || "!=" == b ? Blockly.Ks.ORDER_EQUALITY : Blockly.Ks.ORDER_RELATIONAL,
        d = Blockly.Ks.valueToCode(a, "A", c) || "0";
    a = Blockly.Ks.valueToCode(a, "B", c) || "0";
    return [d + " " + b + " " + a, c]
};
Blockly.Ks.logic_operation = function(a) {
    var b = "AND" == a.getFieldValue("OP") ? "&&" : "||",
        c = "&&" == b ? Blockly.Ks.ORDER_LOGICAL_AND : Blockly.Ks.ORDER_LOGICAL_OR,
        d = Blockly.Ks.valueToCode(a, "A", c);
    a = Blockly.Ks.valueToCode(a, "B", c);
    if (d || a) {
        var e = "&&" == b ? "true" : "false";
        d || (d = e);
        a || (a = e)
    } else a = d = "false";
    return [d + " " + b + " " + a, c]
};
Blockly.Ks.logic_negate = function(a) {
    var b = Blockly.Ks.ORDER_LOGICAL_NOT;
    return ["!" + (Blockly.Ks.valueToCode(a, "BOOL", b) || "true"), b]
};
Blockly.Ks.logic_boolean = function(a) {
    return ["TRUE" == a.getFieldValue("BOOL") ? "true" : "false", Blockly.Ks.ORDER_ATOMIC]
};
Blockly.Ks.logic_null = function(a) {
    return ["null", Blockly.Ks.ORDER_ATOMIC]
};
Blockly.Ks.logic_ternary = function(a) {
    var b = Blockly.Ks.valueToCode(a, "IF", Blockly.Ks.ORDER_CONDITIONAL) || "false",
        c = Blockly.Ks.valueToCode(a, "THEN", Blockly.Ks.ORDER_CONDITIONAL) || "null";
    a = Blockly.Ks.valueToCode(a, "ELSE", Blockly.Ks.ORDER_CONDITIONAL) || "null";
    return [b + " ? " + c + " : " + a, Blockly.Ks.ORDER_CONDITIONAL]
};
Blockly.Ks.loops = {};
Blockly.Ks.controls_repeat_ext = function(a) {
    var b = a.getField("TIMES") ? String(Number(a.getFieldValue("TIMES"))) : Blockly.Ks.valueToCode(a, "TIMES", Blockly.Ks.ORDER_ASSIGNMENT) || "0",
        c = Blockly.Ks.statementToCode(a, "DO");
    c = Blockly.Ks.addLoopTrap(c, a);
    a = "";
    var d = Blockly.Ks.variableDB_.getDistinctName("count", Blockly.VARIABLE_CATEGORY_NAME),
        e = b;
    b.match(/^\w+$/) || Blockly.isNumber(b) || (e = Blockly.Ks.variableDB_.getDistinctName("repeat_end", Blockly.VARIABLE_CATEGORY_NAME),
        a += "var " + e + " = " + b + ";\n");
    return a + ("for (int " + d + " = 0; " + d + " < " + e + "; " + d + "++) {\n" + c + "}\n")
};
Blockly.Ks.controls_repeat = Blockly.Ks.controls_repeat_ext;
Blockly.Ks.controls_whileUntil = function(a) {
    var b = "UNTIL" == a.getFieldValue("MODE"),
        c = Blockly.Ks.valueToCode(a, "BOOL", b ? Blockly.Ks.ORDER_LOGICAL_NOT : Blockly.Ks.ORDER_NONE) || "true==false",
        d = Blockly.Ks.statementToCode(a, "DO");
    d = Blockly.Ks.addLoopTrap(d, a);
    b && (c = "!" + c);
    return "迭代 (" + c + ") {\n" + d + "}\n"
};
Blockly.Ks.controls_for = function(a) {
    var b = Blockly.Ks.variableDB_.getName(a.getFieldValue("VAR"), Blockly.VARIABLE_CATEGORY_NAME),
        c = Blockly.Ks.valueToCode(a, "FROM", Blockly.Ks.ORDER_ASSIGNMENT) || "0",
        d = Blockly.Ks.valueToCode(a, "TO", Blockly.Ks.ORDER_ASSIGNMENT) || "0",
        e = Blockly.Ks.valueToCode(a, "BY", Blockly.Ks.ORDER_ASSIGNMENT) || "1",
        f = Blockly.Ks.statementToCode(a, "DO");
    f = Blockly.Ks.addLoopTrap(f, a);
    if (Blockly.isNumber(c) && Blockly.isNumber(d) &&
        Blockly.isNumber(e)) {
        var g = Number(c) <= Number(d);
        a = "循环 (" + b + " = " + c + "; " + b + (g ? " <= " : " >= ") + d + "; " + b;
        b = Math.abs(Number(e));
        a = (1 == b ? a + (g ? "++" : "--") : a + ((g ? " += " : " -= ") + b)) + (") {\n" + f + "}\n")
    } else a = "", g = c, c.match(/^\w+$/) || Blockly.isNumber(c) || (g = Blockly.Ks.variableDB_.getDistinctName(b + "_start", Blockly.VARIABLE_CATEGORY_NAME), a += "var " + g + " = " + c + ";\n"), c = d, d.match(/^\w+$/) || Blockly.isNumber(d) || (c = Blockly.Ks.variableDB_.getDistinctName(b + "_end", Blockly.VARIABLE_CATEGORY_NAME), a +=
        "var " + c + " = " + d + ";\n"), d = Blockly.Ks.variableDB_.getDistinctName(b + "_inc", Blockly.VARIABLE_CATEGORY_NAME), a += "var " + d + " = ", a = Blockly.isNumber(e) ? a + (Math.abs(e) + ";\n") : a + ("Math.abs(" + e + ");\n"), a = a + ("if (" + g + " > " + c + ") {\n") + (Blockly.Ks.INDENT + d + " = -" + d + ";\n"), a += "}\n", a += "for (" + b + " = " + g + "; " + d + " >= 0 ? " + b + " <= " + c + " : " + b + " >= " + c + "; " + b + " += " + d + ") {\n" + f + "}\n";
    return a
};
Blockly.Ks.controls_forEach = function(a) {
    var b = Blockly.Ks.variableDB_.getName(a.getFieldValue("VAR"), Blockly.VARIABLE_CATEGORY_NAME),
        c = Blockly.Ks.valueToCode(a, "LIST", Blockly.Ks.ORDER_ASSIGNMENT) || "[]",
        d = Blockly.Ks.statementToCode(a, "DO");
    d = Blockly.Ks.addLoopTrap(d, a);
    a = "";
    var e = c;
    c.match(/^\w+$/) || (e = Blockly.Ks.variableDB_.getDistinctName(b + "_list", Blockly.VARIABLE_CATEGORY_NAME), a += "var " + e + " = " + c + ";\n");
    c = Blockly.Ks.variableDB_.getDistinctName(b +
        "_index", Blockly.VARIABLE_CATEGORY_NAME);
    d = Blockly.Ks.INDENT + b + " = " + e + "[" + c + "];\n" + d;
    return a + ("for (var " + c + " in " + e + ") {\n" + d + "}\n")
};
Blockly.Ks.controls_flow_statements = function(a) {
    var b = "";
    Blockly.Ks.STATEMENT_PREFIX && (b += Blockly.Ks.injectId(Blockly.Ks.STATEMENT_PREFIX, a));
    Blockly.Ks.STATEMENT_SUFFIX && (b += Blockly.Ks.injectId(Blockly.Ks.STATEMENT_SUFFIX, a));
    if (Blockly.Ks.STATEMENT_PREFIX) {
        var c = Blockly.Constants.Loops.CONTROL_FLOW_IN_LOOP_CHECK_MIXIN.getSurroundLoop(a);
        c && !c.suppressPrefixSuffix && (b += Blockly.Ks.injectId(Blockly.Ks.STATEMENT_PREFIX,
            c))
    }
    switch (a.getFieldValue("FLOW")) {
        case "BREAK":
            return b + "break;\n";
        case "CONTINUE":
            return b + "continue;\n"
    }
    throw Error("Unknown flow statement.");
};
Blockly.Ks.math = {};
Blockly.Ks.math_number = function(a) {
    a = Number(a.getFieldValue("NUM"));
    return [a, 0 <= a ? Blockly.Ks.ORDER_ATOMIC : Blockly.Ks.ORDER_UNARY_NEGATION]
};
Blockly.Ks.math_arithmetic = function(a) {
    var b = {
            ADD: [" + ", Blockly.Ks.ORDER_ADDITION],
            MINUS: [" - ", Blockly.Ks.ORDER_SUBTRACTION],
            MULTIPLY: [" * ", Blockly.Ks.ORDER_MULTIPLICATION],
            DIVIDE: [" / ", Blockly.Ks.ORDER_DIVISION],
            POWER: [null, Blockly.Ks.ORDER_COMMA]
        }[a.getFieldValue("OP")],
        c = b[0];
    b = b[1];
    var d = Blockly.Ks.valueToCode(a, "A", b) || "0";
    a = Blockly.Ks.valueToCode(a, "B", b) || "0";
    return c ? [d + c + a, b] : ["Math.pow(" + d + ", " + a + ")", Blockly.Ks.ORDER_FUNCTION_CALL]
};
Blockly.Ks.math_single = function(a) {
    var b = a.getFieldValue("OP");
    if ("NEG" == b) return a = Blockly.Ks.valueToCode(a, "NUM", Blockly.Ks.ORDER_UNARY_NEGATION) || "0", "-" == a[0] && (a = " " + a), ["-" + a, Blockly.Ks.ORDER_UNARY_NEGATION];
    a = "SIN" == b || "COS" == b || "TAN" == b ? Blockly.Ks.valueToCode(a, "NUM", Blockly.Ks.ORDER_DIVISION) || "0" : Blockly.Ks.valueToCode(a, "NUM", Blockly.Ks.ORDER_NONE) || "0";
    switch (b) {
        case "ABS":
            var c = "Math.abs(" + a + ")";
            break;
        case "ROOT":
            c = "Math.sqrt(" +
                a + ")";
            break;
        case "LN":
            c = "Math.log(" + a + ")";
            break;
        case "EXP":
            c = "Math.exp(" + a + ")";
            break;
        case "POW10":
            c = "Math.pow(10," + a + ")";
            break;
        case "ROUND":
            c = "Math.round(" + a + ")";
            break;
        case "ROUNDUP":
            c = "Math.ceil(" + a + ")";
            break;
        case "ROUNDDOWN":
            c = "Math.floor(" + a + ")";
            break;
        case "SIN":
            c = "Math.sin(" + a + " / 180 * Math.PI)";
            break;
        case "COS":
            c = "Math.cos(" + a + " / 180 * Math.PI)";
            break;
        case "TAN":
            c = "Math.tan(" + a + " / 180 * Math.PI)"
    }
    if (c) return [c, Blockly.Ks.ORDER_FUNCTION_CALL];
    switch (b) {
        case "LOG10":
            c = "Math.log(" + a +
                ") / Math.log(10)";
            break;
        case "ASIN":
            c = "Math.asin(" + a + ") / Math.PI * 180";
            break;
        case "ACOS":
            c = "Math.acos(" + a + ") / Math.PI * 180";
            break;
        case "ATAN":
            c = "Math.atan(" + a + ") / Math.PI * 180";
            break;
        default:
            throw Error("Unknown math operator: " + b);
    }
    return [c, Blockly.Ks.ORDER_DIVISION]
};
Blockly.Ks.math_constant = function(a) {
    return {
        PI: ["Math.PI", Blockly.Ks.ORDER_MEMBER],
        E: ["Math.E", Blockly.Ks.ORDER_MEMBER],
        GOLDEN_RATIO: ["(1 + Math.sqrt(5)) / 2", Blockly.Ks.ORDER_DIVISION],
        SQRT2: ["Math.SQRT2", Blockly.Ks.ORDER_MEMBER],
        SQRT1_2: ["Math.SQRT1_2", Blockly.Ks.ORDER_MEMBER],
        INFINITY: ["Infinity", Blockly.Ks.ORDER_ATOMIC]
    }[a.getFieldValue("CONSTANT")]
};
Blockly.Ks.math_number_property = function(a) {
    var b = Blockly.Ks.valueToCode(a, "NUMBER_TO_CHECK", Blockly.Ks.ORDER_MODULUS) || "0",
        c = a.getFieldValue("PROPERTY");
    if ("PRIME" == c) return [Blockly.Ks.provideFunction_("mathIsPrime", ["function " + Blockly.Ks.FUNCTION_NAME_PLACEHOLDER_ + "(n) {", "  // https://en.wikipedia.org/wiki/Primality_test#Naive_methods", "  if (n == 2 || n == 3) {", "    return true;", "  }", "  // False if n is NaN, negative, is 1, or not whole.", "  // And false if n is divisible by 2 or 3.",
        "  if (isNaN(n) || n <= 1 || n % 1 != 0 || n % 2 == 0 || n % 3 == 0) {", "    return false;", "  }", "  // Check all the numbers of form 6k +/- 1, up to sqrt(n).", "  for (var x = 6; x <= Math.sqrt(n) + 1; x += 6) {", "    if (n % (x - 1) == 0 || n % (x + 1) == 0) {", "      return false;", "    }", "  }", "  return true;", "}"
    ]) + "(" + b + ")", Blockly.Ks.ORDER_FUNCTION_CALL];
    switch (c) {
        case "EVEN":
            var d = b + " % 2 == 0";
            break;
        case "ODD":
            d = b + " % 2 == 1";
            break;
        case "WHOLE":
            d = b + " % 1 == 0";
            break;
        case "POSITIVE":
            d =
                b + " > 0";
            break;
        case "NEGATIVE":
            d = b + " < 0";
            break;
        case "DIVISIBLE_BY":
            a = Blockly.Ks.valueToCode(a, "DIVISOR", Blockly.Ks.ORDER_MODULUS) || "0", d = b + " % " + a + " == 0"
    }
    return [d, Blockly.Ks.ORDER_EQUALITY]
};
Blockly.Ks.math_change = function(a) {
    var b = Blockly.Ks.valueToCode(a, "DELTA", Blockly.Ks.ORDER_ADDITION) || "0";
    a = Blockly.Ks.variableDB_.getName(a.getFieldValue("VAR"), Blockly.VARIABLE_CATEGORY_NAME);
    return a + " = " + a + " + " + b + ";\n"
};
Blockly.Ks.math_round = Blockly.Ks.math_single;
Blockly.Ks.math_trig = Blockly.Ks.math_single;
Blockly.Ks.math_on_list = function(a) {
    var b = a.getFieldValue("OP");
    switch (b) {
        case "SUM":
            a = Blockly.Ks.valueToCode(a, "LIST", Blockly.Ks.ORDER_MEMBER) || "[]";
            a += ".reduce(function(x, y) {return x + y;})";
            break;
        case "MIN":
            a = Blockly.Ks.valueToCode(a, "LIST", Blockly.Ks.ORDER_COMMA) || "[]";
            a = "Math.min.apply(null, " + a + ")";
            break;
        case "MAX":
            a = Blockly.Ks.valueToCode(a, "LIST", Blockly.Ks.ORDER_COMMA) || "[]";
            a = "Math.max.apply(null, " + a + ")";
            break;
        case "AVERAGE":
            b = Blockly.Ks.provideFunction_("mathMean", ["function " + Blockly.Ks.FUNCTION_NAME_PLACEHOLDER_ + "(myList) {", "  return myList.reduce(function(x, y) {return x + y;}) / myList.length;", "}"]);
            a = Blockly.Ks.valueToCode(a, "LIST", Blockly.Ks.ORDER_NONE) || "[]";
            a = b + "(" + a + ")";
            break;
        case "MEDIAN":
            b = Blockly.Ks.provideFunction_("mathMedian", ["function " + Blockly.Ks.FUNCTION_NAME_PLACEHOLDER_ + "(myList) {", "  var localList = myList.filter(function (x) {return typeof x == 'number';});", "  if (!localList.length) return null;",
                "  localList.sort(function(a, b) {return b - a;});", "  if (localList.length % 2 == 0) {", "    return (localList[localList.length / 2 - 1] + localList[localList.length / 2]) / 2;", "  } else {", "    return localList[(localList.length - 1) / 2];", "  }", "}"
            ]);
            a = Blockly.Ks.valueToCode(a, "LIST", Blockly.Ks.ORDER_NONE) || "[]";
            a = b + "(" + a + ")";
            break;
        case "MODE":
            b = Blockly.Ks.provideFunction_("mathModes", ["function " + Blockly.Ks.FUNCTION_NAME_PLACEHOLDER_ + "(values) {", "  var modes = [];",
                "  var counts = [];", "  var maxCount = 0;", "  for (var i = 0; i < values.length; i++) {", "    var value = values[i];", "    var found = false;", "    var thisCount;", "    for (var j = 0; j < counts.length; j++) {", "      if (counts[j][0] === value) {", "        thisCount = ++counts[j][1];", "        found = true;", "        break;", "      }", "    }", "    if (!found) {", "      counts.push([value, 1]);", "      thisCount = 1;", "    }", "    maxCount = Math.max(thisCount, maxCount);", "  }", "  for (var j = 0; j < counts.length; j++) {",
                "    if (counts[j][1] == maxCount) {", "        modes.push(counts[j][0]);", "    }", "  }", "  return modes;", "}"
            ]);
            a = Blockly.Ks.valueToCode(a, "LIST", Blockly.Ks.ORDER_NONE) || "[]";
            a = b + "(" + a + ")";
            break;
        case "STD_DEV":
            b = Blockly.Ks.provideFunction_("mathStandardDeviation", ["function " + Blockly.Ks.FUNCTION_NAME_PLACEHOLDER_ + "(numbers) {", "  var n = numbers.length;", "  if (!n) return null;", "  var mean = numbers.reduce(function(x, y) {return x + y;}) / n;", "  var variance = 0;",
                "  for (var j = 0; j < n; j++) {", "    variance += Math.pow(numbers[j] - mean, 2);", "  }", "  variance = variance / n;", "  return Math.sqrt(variance);", "}"
            ]);
            a = Blockly.Ks.valueToCode(a, "LIST", Blockly.Ks.ORDER_NONE) || "[]";
            a = b + "(" + a + ")";
            break;
        case "RANDOM":
            b = Blockly.Ks.provideFunction_("mathRandomList", ["function " + Blockly.Ks.FUNCTION_NAME_PLACEHOLDER_ + "(list) {", "  var x = Math.floor(Math.random() * list.length);", "  return list[x];", "}"]);
            a = Blockly.Ks.valueToCode(a,
                "LIST", Blockly.Ks.ORDER_NONE) || "[]";
            a = b + "(" + a + ")";
            break;
        default:
            throw Error("Unknown operator: " + b);
    }
    return [a, Blockly.Ks.ORDER_FUNCTION_CALL]
};
Blockly.Ks.math_modulo = function(a) {
    var b = Blockly.Ks.valueToCode(a, "DIVIDEND", Blockly.Ks.ORDER_MODULUS) || "0";
    a = Blockly.Ks.valueToCode(a, "DIVISOR", Blockly.Ks.ORDER_MODULUS) || "0";
    return [b + " % " + a, Blockly.Ks.ORDER_MODULUS]
};
Blockly.Ks.math_constrain = function(a) {
    var b = Blockly.Ks.valueToCode(a, "VALUE", Blockly.Ks.ORDER_COMMA) || "0",
        c = Blockly.Ks.valueToCode(a, "LOW", Blockly.Ks.ORDER_COMMA) || "0";
    a = Blockly.Ks.valueToCode(a, "HIGH", Blockly.Ks.ORDER_COMMA) || "Infinity";
    return ["Math.min(Math.max(" + b + ", " + c + "), " + a + ")", Blockly.Ks.ORDER_FUNCTION_CALL]
};
Blockly.Ks.math_random_int = function(a) {
    var b = Blockly.Ks.valueToCode(a, "FROM", Blockly.Ks.ORDER_COMMA) || "0";
    a = Blockly.Ks.valueToCode(a, "TO", Blockly.Ks.ORDER_COMMA) || "0";
    return [Blockly.Ks.provideFunction_("mathRandomInt", ["function " + Blockly.Ks.FUNCTION_NAME_PLACEHOLDER_ + "(a, b) {", "  if (a > b) {", "    // Swap a and b to ensure a is smaller.", "    var c = a;", "    a = b;", "    b = c;", "  }", "  return Math.floor(Math.random() * (b - a + 1) + a);",
        "}"
    ]) + "(" + b + ", " + a + ")", Blockly.Ks.ORDER_FUNCTION_CALL]
};
Blockly.Ks.math_random_float = function(a) {
    return ["Math.random()", Blockly.Ks.ORDER_FUNCTION_CALL]
};
Blockly.Ks.math_atan2 = function(a) {
    var b = Blockly.Ks.valueToCode(a, "X", Blockly.Ks.ORDER_COMMA) || "0";
    return ["Math.atan2(" + (Blockly.Ks.valueToCode(a, "Y", Blockly.Ks.ORDER_COMMA) || "0") + ", " + b + ") / Math.PI * 180", Blockly.Ks.ORDER_DIVISION]
};
Blockly.Ks.procedures = {};
Blockly.Ks.procedures_defreturn = function(a) {
    var b = Blockly.Ks.variableDB_.getName(a.getFieldValue("NAME"), Blockly.PROCEDURE_CATEGORY_NAME),
        c = "";
    Blockly.Ks.STATEMENT_PREFIX && (c += Blockly.Ks.injectId(Blockly.Ks.STATEMENT_PREFIX, a));
    Blockly.Ks.STATEMENT_SUFFIX && (c += Blockly.Ks.injectId(Blockly.Ks.STATEMENT_SUFFIX, a));
    c && (c = Blockly.Ks.prefixLines(c, Blockly.Ks.INDENT));
    var d = "";
    Blockly.Ks.INFINITE_LOOP_TRAP && (d = Blockly.Ks.prefixLines(Blockly.Ks.injectId(Blockly.Ks.INFINITE_LOOP_TRAP,
        a), Blockly.Ks.INDENT));
    var e = Blockly.Ks.statementToCode(a, "STACK"),
        f = Blockly.Ks.valueToCode(a, "RETURN", Blockly.Ks.ORDER_NONE) || "",
        g = "";
    e && f && (g = c);
    f && (f = Blockly.Ks.INDENT + "return " + f + ";\n");
    for (var k = [], h = 0; h < a.arguments_.length; h++) k[h] = Blockly.Ks.variableDB_.getName(a.arguments_[h], Blockly.VARIABLE_CATEGORY_NAME);
    c = "function " + b + "(" + k.join(", ") + ") {\n" + c + d + e + g + f + "}";
    c = Blockly.Ks.scrub_(a, c);
    Blockly.Ks.definitions_["%" + b] = c;
    return null
};
Blockly.Ks.procedures_defnoreturn = Blockly.Ks.procedures_defreturn;
Blockly.Ks.procedures_callreturn = function(a) {
    for (var b = Blockly.Ks.variableDB_.getName(a.getFieldValue("NAME"), Blockly.PROCEDURE_CATEGORY_NAME), c = [], d = 0; d < a.arguments_.length; d++) c[d] = Blockly.Ks.valueToCode(a, "ARG" + d, Blockly.Ks.ORDER_COMMA) || "null";
    return [b + "(" + c.join(", ") + ")", Blockly.Ks.ORDER_FUNCTION_CALL]
};
Blockly.Ks.procedures_callnoreturn = function(a) {
    return Blockly.Ks.procedures_callreturn(a)[0] + ";\n"
};
Blockly.Ks.procedures_ifreturn = function(a) {
    var b = "if (" + (Blockly.Ks.valueToCode(a, "CONDITION", Blockly.Ks.ORDER_NONE) || "false") + ") {\n";
    Blockly.Ks.STATEMENT_SUFFIX && (b += Blockly.Ks.prefixLines(Blockly.Ks.injectId(Blockly.Ks.STATEMENT_SUFFIX, a), Blockly.Ks.INDENT));
    a.hasReturnValue_ ? (a = Blockly.Ks.valueToCode(a, "VALUE", Blockly.Ks.ORDER_NONE) || "null", b += Blockly.Ks.INDENT + "return " + a + ";\n") : b += Blockly.Ks.INDENT +
        "return;\n";
    return b + "}\n"
};
Blockly.Ks.texts = {};
Blockly.Ks.text = function(a) {
    return [Blockly.Ks.quote_(a.getFieldValue("TEXT")), Blockly.Ks.ORDER_ATOMIC]
};
Blockly.Ks.text_multiline = function(a) {
    a = Blockly.Ks.multiline_quote_(a.getFieldValue("TEXT"));
    a.includes("\n") && (a = "(" + a + ")");
    return [a, Blockly.Ks.ORDER_ATOMIC]
};
Blockly.Ks.text.forceString_ = function(a) {
    return Blockly.Ks.text.forceString_.strRegExp.test(a) ? a : "String(" + a + ")"
};
Blockly.Ks.text.forceString_.strRegExp = /^\s*'([^']|\\')*'\s*$/;
Blockly.Ks.text_join = function(a) {
    switch (a.itemCount_) {
        case 0:
            return ["''", Blockly.Ks.ORDER_ATOMIC];
        case 1:
            return a = Blockly.Ks.valueToCode(a, "ADD0", Blockly.Ks.ORDER_NONE) || "''", a = Blockly.Ks.text.forceString_(a), [a, Blockly.Ks.ORDER_FUNCTION_CALL];
        case 2:
            var b = Blockly.Ks.valueToCode(a, "ADD0", Blockly.Ks.ORDER_NONE) || "''";
            a = Blockly.Ks.valueToCode(a, "ADD1", Blockly.Ks.ORDER_NONE) || "''";
            a = Blockly.Ks.text.forceString_(b) +
                " + " + Blockly.Ks.text.forceString_(a);
            return [a, Blockly.Ks.ORDER_ADDITION];
        default:
            b = Array(a.itemCount_);
            for (var c = 0; c < a.itemCount_; c++) b[c] = Blockly.Ks.valueToCode(a, "ADD" + c, Blockly.Ks.ORDER_COMMA) || "''";
            a = "[" + b.join(",") + "].join('')";
            return [a, Blockly.Ks.ORDER_FUNCTION_CALL]
    }
};
Blockly.Ks.text_append = function(a) {
    var b = Blockly.Ks.variableDB_.getName(a.getFieldValue("VAR"), Blockly.VARIABLE_CATEGORY_NAME);
    a = Blockly.Ks.valueToCode(a, "TEXT", Blockly.Ks.ORDER_NONE) || "''";
    return b + " += " + Blockly.Ks.text.forceString_(a) + ";\n"
};
Blockly.Ks.text_length = function(a) {
    return [(Blockly.Ks.valueToCode(a, "VALUE", Blockly.Ks.ORDER_FUNCTION_CALL) || "''") + ".length", Blockly.Ks.ORDER_MEMBER]
};
Blockly.Ks.text_isEmpty = function(a) {
    return ["!" + (Blockly.Ks.valueToCode(a, "VALUE", Blockly.Ks.ORDER_MEMBER) || "''") + ".length", Blockly.Ks.ORDER_LOGICAL_NOT]
};
Blockly.Ks.text_indexOf = function(a) {
    var b = "FIRST" == a.getFieldValue("END") ? "indexOf" : "lastIndexOf",
        c = Blockly.Ks.valueToCode(a, "FIND", Blockly.Ks.ORDER_NONE) || "''";
    b = (Blockly.Ks.valueToCode(a, "VALUE", Blockly.Ks.ORDER_MEMBER) || "''") + "." + b + "(" + c + ")";
    return a.workspace.options.oneBasedIndex ? [b + " + 1", Blockly.Ks.ORDER_ADDITION] : [b, Blockly.Ks.ORDER_FUNCTION_CALL]
};
Blockly.Ks.text_charAt = function(a) {
    var b = a.getFieldValue("WHERE") || "FROM_START",
        c = Blockly.Ks.valueToCode(a, "VALUE", "RANDOM" == b ? Blockly.Ks.ORDER_NONE : Blockly.Ks.ORDER_MEMBER) || "''";
    switch (b) {
        case "FIRST":
            return [c + ".charAt(0)", Blockly.Ks.ORDER_FUNCTION_CALL];
        case "LAST":
            return [c + ".slice(-1)", Blockly.Ks.ORDER_FUNCTION_CALL];
        case "FROM_START":
            return a = Blockly.Ks.getAdjusted(a, "AT"), [c + ".charAt(" + a + ")", Blockly.Ks.ORDER_FUNCTION_CALL];
        case "FROM_END":
            return a =
                Blockly.Ks.getAdjusted(a, "AT", 1, !0), [c + ".slice(" + a + ").charAt(0)", Blockly.Ks.ORDER_FUNCTION_CALL];
        case "RANDOM":
            return [Blockly.Ks.provideFunction_("textRandomLetter", ["function " + Blockly.Ks.FUNCTION_NAME_PLACEHOLDER_ + "(text) {", "  var x = Math.floor(Math.random() * text.length);", "  return text[x];", "}"]) + "(" + c + ")", Blockly.Ks.ORDER_FUNCTION_CALL]
    }
    throw Error("Unhandled option (text_charAt).");
};
Blockly.Ks.text.getIndex_ = function(a, b, c) {
    return "FIRST" == b ? "0" : "FROM_END" == b ? a + ".length - 1 - " + c : "LAST" == b ? a + ".length - 1" : c
};
Blockly.Ks.text_getSubstring = function(a) {
    var b = Blockly.Ks.valueToCode(a, "STRING", Blockly.Ks.ORDER_FUNCTION_CALL) || "''",
        c = a.getFieldValue("WHERE1"),
        d = a.getFieldValue("WHERE2");
    if ("FIRST" != c || "LAST" != d)
        if (b.match(/^'?\w+'?$/) || "FROM_END" != c && "LAST" != c && "FROM_END" != d && "LAST" != d) {
            switch (c) {
                case "FROM_START":
                    var e = Blockly.Ks.getAdjusted(a, "AT1");
                    break;
                case "FROM_END":
                    e = Blockly.Ks.getAdjusted(a, "AT1", 1, !1, Blockly.Ks.ORDER_SUBTRACTION);
                    e = b + ".length - " + e;
                    break;
                case "FIRST":
                    e = "0";
                    break;
                default:
                    throw Error("Unhandled option (text_getSubstring).");
            }
            switch (d) {
                case "FROM_START":
                    a = Blockly.Ks.getAdjusted(a, "AT2", 1);
                    break;
                case "FROM_END":
                    a = Blockly.Ks.getAdjusted(a, "AT2", 0, !1, Blockly.Ks.ORDER_SUBTRACTION);
                    a = b + ".length - " + a;
                    break;
                case "LAST":
                    a = b + ".length";
                    break;
                default:
                    throw Error("Unhandled option (text_getSubstring).");
            }
            b = b + ".slice(" + e + ", " + a + ")"
        } else {
            e = Blockly.Ks.getAdjusted(a, "AT1");
            a = Blockly.Ks.getAdjusted(a, "AT2");
            var f =
                Blockly.Ks.text.getIndex_,
                g = {
                    FIRST: "First",
                    LAST: "Last",
                    FROM_START: "FromStart",
                    FROM_END: "FromEnd"
                };
            b = Blockly.Ks.provideFunction_("subsequence" + g[c] + g[d], ["function " + Blockly.Ks.FUNCTION_NAME_PLACEHOLDER_ + "(sequence" + ("FROM_END" == c || "FROM_START" == c ? ", at1" : "") + ("FROM_END" == d || "FROM_START" == d ? ", at2" : "") + ") {", "  var start = " + f("sequence", c, "at1") + ";", "  var end = " + f("sequence", d, "at2") + " + 1;", "  return sequence.slice(start, end);", "}"]) + "(" + b + ("FROM_END" == c || "FROM_START" ==
                c ? ", " + e : "") + ("FROM_END" == d || "FROM_START" == d ? ", " + a : "") + ")"
        }
    return [b, Blockly.Ks.ORDER_FUNCTION_CALL]
};
Blockly.Ks.text_changeCase = function(a) {
    var b = {
        UPPERCASE: ".toUpperCase()",
        LOWERCASE: ".toLowerCase()",
        TITLECASE: null
    }[a.getFieldValue("CASE")];
    a = Blockly.Ks.valueToCode(a, "TEXT", b ? Blockly.Ks.ORDER_MEMBER : Blockly.Ks.ORDER_NONE) || "''";
    return [b ? a + b : Blockly.Ks.provideFunction_("textToTitleCase", ["function " + Blockly.Ks.FUNCTION_NAME_PLACEHOLDER_ + "(str) {", "  return str.replace(/\\S+/g,", "      function(txt) {return txt[0].toUpperCase() + txt.substring(1).toLowerCase();});",
        "}"
    ]) + "(" + a + ")", Blockly.Ks.ORDER_FUNCTION_CALL]
};
Blockly.Ks.text_trim = function(a) {
    var b = {
        LEFT: ".replace(/^[\\s\\xa0]+/, '')",
        RIGHT: ".replace(/[\\s\\xa0]+$/, '')",
        BOTH: ".trim()"
    }[a.getFieldValue("MODE")];
    return [(Blockly.Ks.valueToCode(a, "TEXT", Blockly.Ks.ORDER_MEMBER) || "''") + b, Blockly.Ks.ORDER_FUNCTION_CALL]
};
Blockly.Ks.text_print = function(a) {
    return "打印 " + (Blockly.Ks.valueToCode(a, "TEXT", Blockly.Ks.ORDER_NONE) || "\"\"") + ";\n"
};
Blockly.Ks.text_prompt_ext = function(a) {
    var b = "window.prompt(" + (a.getField("TEXT") ? Blockly.Ks.quote_(a.getFieldValue("TEXT")) : Blockly.Ks.valueToCode(a, "TEXT", Blockly.Ks.ORDER_NONE) || "''") + ")";
    "NUMBER" == a.getFieldValue("TYPE") && (b = "Number(" + b + ")");
    return [b, Blockly.Ks.ORDER_FUNCTION_CALL]
};
Blockly.Ks.text_prompt = Blockly.Ks.text_prompt_ext;
Blockly.Ks.text_count = function(a) {
    var b = Blockly.Ks.valueToCode(a, "TEXT", Blockly.Ks.ORDER_MEMBER) || "''";
    a = Blockly.Ks.valueToCode(a, "SUB", Blockly.Ks.ORDER_NONE) || "''";
    return [Blockly.Ks.provideFunction_("textCount", ["function " + Blockly.Ks.FUNCTION_NAME_PLACEHOLDER_ + "(haystack, needle) {", "  if (needle.length === 0) {", "    return haystack.length + 1;", "  } else {", "    return haystack.split(needle).length - 1;", "  }", "}"]) + "(" + b + ", " + a + ")", Blockly.Ks.ORDER_SUBTRACTION]
};
Blockly.Ks.text_replace = function(a) {
    var b = Blockly.Ks.valueToCode(a, "TEXT", Blockly.Ks.ORDER_MEMBER) || "''",
        c = Blockly.Ks.valueToCode(a, "FROM", Blockly.Ks.ORDER_NONE) || "''";
    a = Blockly.Ks.valueToCode(a, "TO", Blockly.Ks.ORDER_NONE) || "''";
    return [Blockly.Ks.provideFunction_("textReplace", ["function " + Blockly.Ks.FUNCTION_NAME_PLACEHOLDER_ + "(haystack, needle, replacement) {", '  needle = needle.replace(/([-()\\[\\]{}+?*.$\\^|,:#<!\\\\])/g,"\\\\$1")',
        '                 .replace(/\\x08/g,"\\\\x08");', "  return haystack.replace(new RegExp(needle, 'g'), replacement);", "}"
    ]) + "(" + b + ", " + c + ", " + a + ")", Blockly.Ks.ORDER_MEMBER]
};
Blockly.Ks.text_reverse = function(a) {
    return [(Blockly.Ks.valueToCode(a, "TEXT", Blockly.Ks.ORDER_MEMBER) || "''") + ".split('').reverse().join('')", Blockly.Ks.ORDER_MEMBER]
};
Blockly.Ks.variables = {};
Blockly.Ks.variables_get = function(a) {
    return [Blockly.Ks.variableDB_.getName(a.getFieldValue("VAR"), Blockly.VARIABLE_CATEGORY_NAME), Blockly.Ks.ORDER_ATOMIC]
};
Blockly.Ks.variables_set = function(a) {
    var b = Blockly.Ks.valueToCode(a, "VALUE", Blockly.Ks.ORDER_ASSIGNMENT) || "0";
    return Blockly.Ks.variableDB_.getName(a.getFieldValue("VAR"), Blockly.VARIABLE_CATEGORY_NAME) + " = " + b + ";\n"
};
Blockly.Ks.variablesDynamic = {};
Blockly.Ks.variables_get_dynamic = Blockly.Ks.variables_get;
Blockly.Ks.variables_set_dynamic = Blockly.Ks.variables_set;

/*Blockly.Ks.string_length = function(a) {
    var argument0 = Blockly.Ks.valueToCode(a, 'VALUE',
        Blockly.Ks.ORDER_FUNCTION_CALL) || '\'\'';
    return [argument0 + '.length', Blockly.Ks.ORDER_MEMBER];
};*/

Blockly.Ks.import_game_libs = function(a) {
	var r = '包含 "libs\\kslib\\commLibs.ks";\n';
	r+= '包含 "libs\\kslib\\gameLibs.ks";\n\n';
  return r;
};

Blockly.Ks.create_map = function(a) {
	//var number_dx = a.getFieldValue('DX');
	//var number_dy = a.getFieldValue('DY');
	
	/*var b = Blockly.Ks.variableDB_.getName(a.getFieldValue("INIT"), Blockly.VARIABLE_CATEGORY_NAME),
	c = Blockly.Ks.valueToCode(a, "LIST", Blockly.Ks.ORDER_ASSIGNMENT) || "[]",
    d = Blockly.Ks.statementToCode(a, "DO");*/
	/*d = Blockly.Ks.addLoopTrap(d, a);
	a = "";
	var e = c;
	c.match(/^\w+$/) || (e = Blockly.Ks.variableDB_.getDistinctName(b + "_list", Blockly.VARIABLE_CATEGORY_NAME), a += "var " + e + " = " + c + ";\n");
	c = Blockly.Ks.variableDB_.getDistinctName(b +
	    "_index", Blockly.VARIABLE_CATEGORY_NAME);
	d = Blockly.Ks.INDENT + b + " = " + e + "[" + c + "];\n" + d;*/
	// return a + ("for (var " + c + " in " + e + ") {\n" + d + "}\n")
	var code = '包含 "demo\\pb\\map.ks";\n\n';
	var statements_init = Blockly.Ks.statementToCode(a, 'INIT');
	
	code += '游戏地图.设置名称("推箱子");\n';
	code += statements_init + '\n';
	code += '游戏地图.展示();';
	return code;
};

Blockly.Ks.placement_robot = function(a) {
	var number_rdx = a.getFieldValue('RDX');
	var number_rdy = a.getFieldValue('RDY');
	var code = '游戏地图.设置机器人位置('+number_rdx+', '+number_rdy+');\n';
	return code;
};

Blockly.Ks.robot_control = function(a) {
	var str_rup = a.getFieldValue('RUP');
	var str_rdown = a.getFieldValue('RDOWN');
	var str_rleft = a.getFieldValue('RLEFT');
	var str_rright = a.getFieldValue('RRIGHT');
	var code = '游戏地图.设置机器人方向控制("'+str_rup+'","'+str_rdown+'","'+str_rleft+'","'+str_rright+'");\n';
	return code;
};

Blockly.Ks.add_obstacle = function(a) {
	var number_odx = a.getFieldValue('ODX');
	var number_ody = a.getFieldValue('ODY');
	var code = '游戏地图.添加障碍('+number_odx+', '+number_ody+');\n';
	return code;
};

Blockly.Ks.add_obstacle_h = function(a) {
	var number_odx1 = a.getFieldValue('ODX1');
	var number_odx2 = a.getFieldValue('ODX2');
	var number_ody = a.getFieldValue('ODY');
	var code = '游戏地图.添加多个水平障碍('+number_ody+', '+number_odx1+', '+number_odx2+');\n';
	return code;
};

Blockly.Ks.add_obstacle_v = function(a) {
	var number_odx = a.getFieldValue('ODX');
	var number_ody1 = a.getFieldValue('ODY1');
	var number_ody2 = a.getFieldValue('ODY2');
	var code = '游戏地图.添加多个垂直障碍('+number_odx+', '+number_ody1+', '+number_ody2+');\n';
	return code;
};

Blockly.Ks.add_box = function(a) {
	var number_bdx = a.getFieldValue('BDX');
	var number_bdy = a.getFieldValue('BDY');
	var code = '游戏地图.添加物品('+number_bdx+', '+number_bdy+');\n';
	return code;
};

Blockly.Ks.add_target = function(a) {
	var number_tdx = a.getFieldValue('TDX');
	var number_tdy = a.getFieldValue('TDY');
	var code = '游戏地图.添加目标位置('+number_tdx+', '+number_tdy+');\n';
	return code;
};

Blockly.Ks.import_screen_libs = function(a) {
	var r = '包含 "libs\\kslib\\commLibs.ks";\n';
	r+= '包含 "libs\\kslib\\screenLibs.ks";\n\n';
  return r;
};

Blockly.Ks.open_serial_port = function(a) {
	var str_sp = a.getFieldValue('SP');
	var number_br = a.getFieldValue('BR');
	var code = '连接串口("'+str_sp+'",'+number_br+');\n';
	return code;
};

Blockly.Ks.close_serial_port = function(a) {
	var code = '断开串口();\n';
	return code;
};

Blockly.Ks.waitting = function(a) {
	var number_ms = a.getFieldValue('MS');
	var code = '等待('+number_ms+');\n';
	return code;
};

Blockly.Ks.clear_screen = function(a) {
	var code = '清屏();\n';
	return code;
};

Blockly.Ks.end_and_display = function(a) {
	var code = '结束并显示();\n';
	return code;
};

Blockly.Ks.get_time_str = function(a) {
	var code = '取得当前时间字符串()';
	return [code, Blockly.Ks.ORDER_NONE];
};

Blockly.Ks.out_pixel = function(a) {
	var number_sdx = a.getFieldValue('SDX');
	var number_sdy = a.getFieldValue('SDY');
	var str_scolor = Blockly.Ks.valueToCode(a, 'SCOLOR', Blockly.Ks.ORDER_ATOMIC);
	var code = '输出点('+number_sdx+','+number_sdy+','+str_scolor+');\n';
	return code;
};

Blockly.Ks.out_str = function(a) {
	var str_str = Blockly.Ks.valueToCode(a, 'SSTR', Blockly.Ks.ORDER_NONE);
	var number_sdx = a.getFieldValue('SDX');
	var number_sdy = a.getFieldValue('SDY');
	var str_scolor = Blockly.Ks.valueToCode(a, 'SCOLOR', Blockly.Ks.ORDER_ATOMIC);
	var code = '输出文本('+number_sdx+','+number_sdy+','+str_scolor+','+str_str+');\n';
	return code;
};

Blockly.Ks.out_vline = function(a) {
	var number_sl = a.getFieldValue('SL');
	var number_sdx = a.getFieldValue('SDX');
	var number_sdy = a.getFieldValue('SDY');
	var str_scolor = Blockly.Ks.valueToCode(a, 'SCOLOR', Blockly.Ks.ORDER_ATOMIC);
	var code = '输出垂直线('+number_sdx+','+number_sdy+','+str_scolor+','+number_sl+');\n';
	return code;
};

Blockly.Ks.out_hline = function(a) {
	var number_sl = a.getFieldValue('SL');
	var number_sdx = a.getFieldValue('SDX');
	var number_sdy = a.getFieldValue('SDY');
	var str_scolor = Blockly.Ks.valueToCode(a, 'SCOLOR', Blockly.Ks.ORDER_ATOMIC);
	var code = '输出水平线('+number_sdx+','+number_sdy+','+str_scolor+','+number_sl+');\n';
	return code;
};
